openapi: 3.0.0
info:
  title: Hello World
  version: '2.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /hello_world:
    get:
      summary: Get Hello World
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Hello-World-V2.v1.yaml
              examples:
                Success:
                  value:
                    country:
                      - name: Indonesia
                        created: 1593765050086
                        gdp: '1000'
      operationId: get-hello_world
    post:
      summary: POST Hello World
      tags: []
      operationId: post-hello_world
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                country:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      created:
                        type: number
                      gdp:
                        type: string
            examples:
              example-1: {}
        description: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Hello-World-V2.v1.yaml
              examples:
                Success:
                  value:
                    country:
                      - name: Indonesia
                        created: 1593765050086
                        gdp: '1000'
components:
  schemas: {}
